project:
  name: ImageClassification
  experiment: exp-1
  task: classification

data:
  location: "./data/MNISTMini/"
  img-res: [28,28]
  greyscale: true

training:
  epochs: 5
  batch_size: 64
  learning_rate: 0.01

validation:
  test_size: 0.3
  folds: 2