project:
  name: ImageClassification
  task: classification

data:
  location: data/MNISTMini/
  img-res: [28,28]
  greyscale: false

training:
  max_epochs: 1
  batch_size: [64, 128]

optimizer:
  learning_rate: [0.0001, 0.01]
  step_size: 30
  gamma: 0.1
  number_trials: 3

validation:
  test_size: 0.2
  folds: 2

wandb:
  key: 24b2e4eab14cdb91e7d3c8177f62af82c5911723 # ${{ secrets.WANDB_KEY }}