project:
  name: ImageClassification
  task: classification

data:
  location: data/source/MNISTMini/
  img-res: [28,28]
  greyscale: true

model_architecture:
  name: SimpleModel

training:
  max_epochs: 1
  batch_size: 64

optimization:
  optimizer: Adam
  learning_rate: 0.001
  loss_fnc: NLLLoss

tuning:
  number_trials: 3

validation:
  test_size: 0.2 # ignored if a presplit test dataset is provided
  folds: 2
