project:
  name: ImageClassification
  experiment: exp-1
  task: classification

data:
  location: "./data/image-classification/"
  img-res: [48,48]
  greyscale: true

training:
  epochs: 20
  batch_size: 32
  learning_rate: 0.005

validation:
  test_size: 0.3
  folds: null